### ISSUE TITLE
ModPagespeedFileCacheSizeKb appears to not be working

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pagespeed/mod_pagespeed#753]
```
What steps will reproduce the problem?
1. Set ModPagespeedFileCacheSizeKb in the /etc/httpd/conf.d/pagespeed.conf to 
the following:

ModPagespeedFileCacheSizeKb          262144
ModPagespeedFileCacheCleanIntervalMs 3600000

2. Restart apache
3. Wait

What is the expected output? What do you see instead?
The size of the folder /var/cache/mod_pagespeed to not be so big.

I have the folder mounted to a tmpfs mount so the objects can be cached in RAM, 
yet its going way over the space I have alloted.
tmpfs                 512M  512M     0 100% /var/cache/mod_pagespeed

[root@server ~]# du -sh /var/cache/mod_pagespeed/*
4.0K    /var/cache/mod_pagespeed/!clean!time!
398M    /var/cache/mod_pagespeed/http,3A
11M     /var/cache/mod_pagespeed/prop_page
104M    /var/cache/mod_pagespeed/rname

What version of the product are you using (please check X-Mod-Pagespeed
header)?
[root@server ~]# rpm -qa | grep pagespeed
mod-pagespeed-stable-1.4.26.3-3101

On what operating system?
Cloudlinx 5.9 PAE

Which version of Apache?
[root@server ~]# rpm -qa | grep httpd
httpd-2.2.3-76.el5_9.cloudlinux.2

Which MPM?
U/N

URL of broken page:
N/A
```

Original issue reported on code.google.com by `stevencr...@gmail.com` on 26 Jul 2013 at 8:48

**Comment by leotm** [comment]
Just read this [this](https://developers.google.com/speed/pagespeed/module/console#cache-miss). Could you explain why the **Remedy** is 

> about 5 times as large as your website content

 and why one would want to

> store all of the original resources and various versions of rewritten resources

I also noticed the SiteGround default config is `pagespeed EnableFilters extend_cache;` and wondering the reasoning behind this.

**Comment by hillsp** [comment]
We suggest "5 times" because PageSpeed can recompress an image into a number of different formats, including webp for both desktop & mobile and jpeg for both desktop & mobile. Because images are usually the bulk of the data in a site, this means the cache can become significantly larger than the original site.

If you use LoadFromFile, PageSpeed won't store the original version, but you probably want it to store all the recompressed images since they need a lot of CPU to produce each time!

I can't speak to anything about SiteGround, I'm afraid.
